### ISSUE TITLE
Support tailwind 2 class names?

### ISSUE THREAD

**Issue by rintcius** [gillchristian/tailwind-purs#1]
I was trying with tailwind 2.0.1 and `gen-available-classes` is generating rows like:

```
32xl;32xl

bottom3.5;bottom-3.5
```

This is then generating invalid PureScript. The first because it starts with a digit and the second because of the `.`

**Comment by gillchristian** [comment]
Nice catch, and thanks for reporting.

I need to update my projects to Tailwind v2. Hopefully I'll manage to do it this week and push a fix for this as well.

**Comment by gillchristian** [comment]
I started to work on this. Here are the transformations I'm applying.

https://github.com/gillchristian/tailwind-purs/blob/bbf0b780dbfc0a49f511c4d9cbc7ff72225a7e8c/test/Spec.hs#L24-L49

If you have suggestions let me know.

Specially the new cases:

- prefixing with `_` when starting with a number (`32xl => _32xl`)
- replacing dot with 'p' (`foo-3.5 => foo3p5`)
